module Timer #(
parameter Width = 32,

parameter GEN1_PIPEWIDTH = 8 ,	
parameter GEN2_PIPEWIDTH = 8 ,	
parameter GEN3_PIPEWIDTH = 8 ,	
parameter GEN4_PIPEWIDTH = 8 ,	
parameter GEN5_PIPEWIDTH = 8 	

)
(
input [2:0]Gen,
input Reset,
input Pclk,
input Enable,
input Start,
input [2:0]TimerIntervalCode, //001 -> 12ms
output TimeOut
);
reg [Width-1:0] Tick;
reg [Width-1:0] TimerIntervalBase;
reg [Width-1:0] TimerInterval;
parameter Gen1 = 3'b001,Gen2 = 3'b010,Gen3 = 3'b011,Gen4 = 3'b100,Gen5 = 3'b101;
parameter t12ms= 3'b001,t24ms = 3'b010,t48ms = 3'b011,t2ms = 3'b100,t8ms = 3'b101,t0ms = 3'b000;
always @ *
begin
	case({TimerIntervalCode})
		t12ms:begin  
			TimerIntervalBase= 32'h000B71B0 ;//750000 cycle => Gen1 32bit width , 12ms 
		end
		
		t24ms:begin  
			TimerIntervalBase= 32'h16E360 ;//1500000 cycle => Gen1 32bit width , 24ms 
		end

		t48ms:begin  
			TimerIntervalBase= 32'h2DC6C0 ;//3000000cycle => Gen1 48bit width , 48ms 
		end
		t8ms:begin  
			TimerIntervalBase= 32'h7A120 ;//500000cycle => Gen1 48bit width , 48ms 
		end

		t2ms:begin  
			TimerIntervalBase= 32'h1E848 ;//125000 cycle => Gen1 32bit width , 2ms 
		end	
		t0ms:begin  
			TimerIntervalBase= 32'h00000000;//0cycle => Gen1 32bit width , 0ms 
		end
		// BUGFIX-015:
		// Original issue: this case statement covered only 6 of the 8 possible
		// TimerIntervalCode values (3'b110 and 3'b111 were missing), so
		// TimerIntervalBase was inferred as a latch for those encodings.
		// Root cause: no default branch.
		// Fix: add a default that selects a zero interval (immediate timeout
		// disabled by Start/Enable semantics), which is also the reset-friendly
		// value. Codes 110/111 are not generated by any LTSSM today.
		// Verified by: yosys proc;check (no latch reported for TimerIntervalBase).
		default:begin
			TimerIntervalBase= 32'h00000000;
		end
	endcase
end

//for higher Generation multiply the base value by 2 (shift left)
always @ *
begin
	case(Gen)
		Gen1:begin //Gen1  
			 case(GEN1_PIPEWIDTH)
			 32:TimerInterval=TimerIntervalBase<<0<<0 ; //multiply base by 1 (Gen1 32 bit)
			 16:TimerInterval=TimerIntervalBase<<0<<1 ; //multiply base by 2 (Gen1 16 bit)
			 8 :TimerInterval=TimerIntervalBase<<0<<2 ; //multiply base by 4 (Gen1 8 bit)
			 endcase
		end
		Gen2:begin //Gen2  
			 case(GEN2_PIPEWIDTH)
			 32:TimerInterval=TimerIntervalBase<<1<<0 ; //multiply base by 2 for Gen2 (Gen2 32 bit)
			 16:TimerInterval=TimerIntervalBase<<1<<1 ; //multiply base by 2 for Gen2 and another 2 for 16 bit width (Gen2 16 bit)
			 8 :TimerInterval=TimerIntervalBase<<1<<2 ; ///multiply base by 2 for Gen2 and another 4 for 16 bit width (Gen2 32 bit)
			 endcase
		end
		Gen3:begin //Gen3  
			 case(GEN3_PIPEWIDTH)
			 32:TimerInterval=TimerIntervalBase<<2<<0 ; //multiply base by 4 for Gen2 (Gen3 32 bit)
			 16:TimerInterval=TimerIntervalBase<<2<<1 ; //multiply base by 4 for Gen2 and another 2 for 16 bit width (Gen3 16 bit)
			 8 :TimerInterval=TimerIntervalBase<<2<<2 ; //multiply base by 4 for Gen2 and another 4 for 16 bit width (Gen3 32 bit)
			 endcase
		end
		Gen4:begin //Gen3  
			 case(GEN4_PIPEWIDTH)
			 32:TimerInterval=TimerIntervalBase<<3<<0 ; //multiply base by 4 for Gen2 (Gen3 32 bit)
			 16:TimerInterval=TimerIntervalBase<<3<<1 ; //multiply base by 4 for Gen2 and another 2 for 16 bit width (Gen3 16 bit)
			 8 :TimerInterval=TimerIntervalBase<<3<<2 ; //multiply base by 4 for Gen2 and another 4 for 16 bit width (Gen3 32 bit)
			 endcase
		end
		// BUGFIX-030:
		// Original issue: Gen5 used <<5 (x32) while Gen1..Gen4 follow the
		// doubling pattern <<0..<<3 (x1, x2, x4, x8); the comments in the
		// other branches show the intent "multiply the base by 2 per
		// generation". <<5 broke that pattern and made every Gen5 timeout
		// (e.g. the 12ms Detect timer) roughly 2x longer than the x16
		// approximation used for Gen4.
		// Root cause: shift-amount typo (5 instead of 4).
		// Fix: use <<4 so Gen5 continues the per-generation doubling series.
		// Verified by: review (timer equations); slang compile.
		Gen5:begin //Gen5  
			 case(GEN5_PIPEWIDTH)
			 32:TimerInterval=TimerIntervalBase<<4<<0 ; //multiply base by 16 for Gen5 (Gen5 32 bit)
			 16:TimerInterval=TimerIntervalBase<<4<<1 ; //multiply base by 16 for Gen5 and another 2 for 16 bit width (Gen5 16 bit)
			 8 :TimerInterval=TimerIntervalBase<<4<<2 ; //multiply base by 16 for Gen5 and another 4 for 8 bit width (Gen5 8 bit)
			 // BUGFIX-039: inner width cases covered only 32/16/8, so any
			 // other GENx_PIPEWIDTH parameterization latched TimerInterval.
			 // Root cause: incomplete case. Fix: default behaves like the
			 // 32-bit-width entry (no extra width scaling). Verified by:
			 // yosys proc (no $dlatch in Timer anymore).
			 default:TimerInterval=TimerIntervalBase<<4<<0 ;
			 endcase
		end
		// BUGFIX-039: the outer case covered only Gen1..Gen5 (5 of the 8
		// possible Gen encodings), latching TimerInterval for the others.
		// Root cause: incomplete case. Fix: default treats an unknown
		// generation like Gen1 (base interval, no generation scaling).
		// Verified by: yosys proc (no $dlatch in Timer anymore).
		default:begin
			TimerInterval=TimerIntervalBase;
		end
	endcase
end
assign TimeOut = (Start)? 0:(Tick >= TimerInterval)? 1:0 ;
always @(posedge Pclk)
begin
if (!Reset||Start) begin
Tick <= 0;
end
else if (Enable)begin
Tick <=Tick +1;
end
end
endmodule